# The comments in this file show via example how to override some of the most popular set of options.
# However, it is possible to override any Docker configuration setting, for example Port mappings, by adding the override here.
version: '3.6'
services:
  #postgres:
    #deploy:
    #  this placement constraint example requires running:  docker node update --label-add type=db xxxNodeId
    #  placement:
    #    constraints:
    #    - node.labels.type == db
  #authentication:
  #webapp:
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
    #deploy:
    #  resources:
    #    limits: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #    reservations: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #  placement:
    #    constraints:
    #    - node.labels.type == db
  #scan:
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
    #deploy:
    #  resources:
    #    limits: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #    reservations: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #  replicas: REPLACE_WITH_NUM_REPLICAS
  #jobrunner:
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
    #deploy:
    #  resources:
    #    limits: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #    reservations: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #  replicas: REPLACE_WITH_NUM_REPLICAS  #postgres:
  #logstash:
    #deploy:
    #  placement:
    #    constraints:
    #    - node.labels.type == db
  #registration:
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
  #webserver:
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
    #  - WEBSERVER_CUSTOM_CERT_FILE
    #  - WEBSERVER_CUSTOM_KEY_FILE
  #uploadcache:
    #secrets:
    #  - SEAL_KEY
#secrets:
#  HUB_PROXY_PASSWORD_FILE:
#    external: true
#    name: "hub_PROXY_PASSWORD_FILE"
#  WEBSERVER_CUSTOM_CERT_FILE:
#    external: true
#    name: "hub_WEBSERVER_CUSTOM_CERT_FILE"
#  WEBSERVER_CUSTOM_KEY_FILE:
#    external: true
#    name: "hub_WEBSERVER_CUSTOM_KEY_FILE"
#  SEAL_KEY:
#     external: true
#     name: "hub_SEAL_KEY"
