postgres:
  resources:
    requests:
      cpu: "3000m"
      memory: "12288Mi"

jobrunner:
  replicas: 10
  hubMaxMemory: "12288m"
  maxPeriodicThreads: 8
  maxPeriodicPrefetch: 4
  maxOndemandThreads: 24
  maxOndemandPrefetch: 16
  resources:
    limits:
      cpu: "1000m"
      memory: "13824Mi"

scan:
  replicas: 5
  hubMaxMemory: "8192m"
  resources:
    limits:
      memory: "9728Mi"

webapp:
  hubMaxMemory: "18192m"
  resources:
    requests:
      cpu: "3000m"
    limits:
      memory: "19728Mi"

webserver:
  resources:
    limits:
      memory: "2048Mi"

webui:
  resources:
    requests:
      cpu: "500m"
    limits:
      cpu: "1000m"
      memory: "640Mi"

bomengine:
  replicas: 6
  hubMaxMemory: "12288m"
  resources:
    requests:
      memory: "1536Mi"
    limits:
      memory: "13824Mi"

matchengine:
  replicas: 5
  hubMaxMemory: "1024m"
  resources:
    requests:
      memory: "1024Mi"
      cpu: "500m"
    limits:
      memory: "1536Mi"
      cpu: "1000m"
