postgres:
  resources:
    requests:
      cpu: "3000m"
      memory: "12288Mi"

jobrunner:
  replicas: 5
  hubMaxMemory: "10240m"
  maxPeriodicThreads: 6
  maxPeriodicPrefetch: 3
  maxOndemandThreads: 20
  maxOndemandPrefetch: 14
  resources:
    limits:
      cpu: "1000m"
      memory: "11776Mi"

redis:
  replicas: 1
  resources:
    limits:
      memory: "11264Mi"

scan:
  replicas: 5
  hubMaxMemory: "8192m"
  resources:
    limits:
      memory: "9728Mi"

webapp:
  hubMaxMemory: "18192m"
  resources:
    requests:
      cpu: "3000m"
    limits:
      memory: "19728Mi"

webserver:
  resources:
    limits:
      memory: "2048Mi"

webui:
  resources:
    requests:
      cpu: "500m"
    limits:
      cpu: "1000m"
      memory: "1024Mi"

bomengine:
  replicas: 6
  hubMaxMemory: "12288m"
  resources:
    requests:
      memory: "1536Mi"
    limits:
      memory: "13824Mi"

matchengine:
  replicas: 10
  hubMaxMemory: "12288m"
  resources:
    requests:
      memory: "1536Mi"
      cpu: "500m"
    limits:
      memory: "13824Mi"
      cpu: "1000m"
