{{- $_ :=  set . "serviceName" "blackduck-matchengine" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: matchengine
  name: {{ .Release.Name }}-blackduck-matchengine
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-8443
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "bd.selectorLabelsWithoutVersion" . | nindent 4 }}
    component: matchengine
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: matchengine
  name: {{ .Release.Name }}-blackduck-matchengine
  namespace: {{ .Release.Namespace }}
spec:
  {{- if eq .Values.status "Running" }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      {{- include "bd.selectorLabelsWithoutVersion" . | nindent 6 }}
      component: matchengine
  strategy:

    type: Recreate
  template:
    metadata:
      labels:
        {{- include "bd.selectorLabels" . | nindent 8 }}
        component: matchengine
      annotations:
        {{- include "bd.prometheus.common.annotations" . | nindent 8 }}
        checksum/blackduck-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/postgres-config: {{ include (print $.Template.BasePath "/postgres-config.yaml") . | sha256sum }}
      name: {{ .Release.Name }}-blackduck-matchengine
    spec:
      {{- if .Values.enableInitContainer }}
      initContainers:
      {{- include "bd.datadog.java.initcontainer" . | indent 6 }}
      - name: synopsys-init
        {{- if .Values.init.registry }}
        image: {{ .Values.init.registry }}/synopsys-init:{{ .Values.init.imageTag }}
        {{- else }}
        image: {{ .Values.registry }}/synopsys-init:{{ .Values.init.imageTag }}
        {{- end}}
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: HUB_POSTGRES_HOST
              name: {{ .Release.Name }}-blackduck-db-config
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: HUB_POSTGRES_PORT
              name: {{ .Release.Name }}-blackduck-db-config
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: HUB_POSTGRES_CONNECTION_ADMIN
              name: {{ .Release.Name }}-blackduck-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: HUB_POSTGRES_ADMIN_PASSWORD_FILE
              name: {{ .Release.Name }}-blackduck-db-creds
        - name: POSTGRES_SSL_MODE
          valueFrom:
            configMapKeyRef:
              key: HUB_POSTGRES_ENABLE_SSL
              name: {{ .Release.Name }}-blackduck-db-config
        args:
        - "--postgres-database={{ .Values.init.database }}" # Postgres database name
        - "--postgres-host=$(POSTGRES_HOST)" # Postgres database host
        - "--postgres-password=$(POSTGRES_PASSWORD)" # Postgres database password
        - "--postgres-port=$(POSTGRES_PORT)" # Postgres database port
        - "--postgres-user=$(POSTGRES_USER)" # Postgres database user
        - "--postgres-ssl-mode=$(POSTGRES_SSL_MODE)" # Postgres SSL mode
        imagePullPolicy: Always
        {{- with .Values.init.securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - env:
        - name: HUB_MAX_MEMORY
          value: {{ .Values.matchengine.hubMaxMemory }}
        {{- include "bd.datadog.java.env" . | indent 8 }}
        - name: DD_ENABLED
          value: {{ .Values.datadog.enabled | quote }}
        - name: HUB_MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
          value: {{ .Values.metrics.enabled | quote }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-db-config
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-config
        {{- if .Values.matchengine.registry }}
          {{- if .Values.matchengine.imageTag }}
        image: {{ .Values.matchengine.registry }}/blackduck-matchengine:{{ .Values.matchengine.imageTag }}
          {{- else }}
        image: {{ .Values.matchengine.registry }}/blackduck-matchengine:{{ .Values.imageTag }}
          {{- end}}
        {{- else }}
          {{- if .Values.matchengine.imageTag }}
        image: {{ .Values.registry }}/blackduck-matchengine:{{ .Values.matchengine.imageTag }}
          {{- else }}
        image: {{ .Values.registry }}/blackduck-matchengine:{{ .Values.imageTag }}
          {{- end}}
        {{- end}}
        imagePullPolicy: Always
        {{- include "matchengineLivenessProbe" . | nindent 8 }}
        name: matchengine
        ports:
        - containerPort: 8443
          protocol: TCP
        resources:
          {{- toYaml .Values.matchengine.resources | nindent 12 }}
        {{- with .Values.matchengine.securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
        volumeMounts:
        {{- include "bd.datadog.java.volumemount" . | indent 8 }}
        - mountPath: /tmp/secrets/HUB_POSTGRES_ADMIN_PASSWORD_FILE
          name: db-passwords
          subPath: HUB_POSTGRES_ADMIN_PASSWORD_FILE
        - mountPath: /tmp/secrets/HUB_POSTGRES_USER_PASSWORD_FILE
          name: db-passwords
          subPath: HUB_POSTGRES_USER_PASSWORD_FILE
        - mountPath: /opt/blackduck/hub/blackduck-matchengine/security
          name: dir-matchengine-security
        {{- include "common.volume.mount" . | indent 8 }}
      dnsPolicy: ClusterFirst
      {{- include "bd.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.matchengine.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.matchengine.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.matchengine.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      restartPolicy: Always
      {{- if .Values.matchengine.podSecurityContext }}
      {{- with .Values.matchengine.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- else }}
      {{- include "bd.podSecurityContext" . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-blackduck-service-account
      volumes:
      {{- include "bd.datadog.java.volume" . | indent 6 }}
      - name: db-passwords
        secret:
          defaultMode: 420
          items:
          - key: HUB_POSTGRES_ADMIN_PASSWORD_FILE
            mode: 420
            path: HUB_POSTGRES_ADMIN_PASSWORD_FILE
          - key: HUB_POSTGRES_USER_PASSWORD_FILE
            mode: 420
            path: HUB_POSTGRES_USER_PASSWORD_FILE
          secretName: {{ .Release.Name }}-blackduck-db-creds
      - emptyDir: {}
        name: dir-matchengine-security
      {{- include "common.volumes" . | indent 6 }}

{{- define "matchengineLivenessProbe" -}}
{{- if .Values.enableLivenessProbe -}}
livenessProbe:
  exec:
    command:
    - /usr/local/bin/docker-healthcheck.sh
    - https://127.0.0.1:8443/api/health-checks/liveness
    - /opt/blackduck/hub/blackduck-matchengine/security/root.crt
    - /opt/blackduck/hub/blackduck-matchengine/security/blackduck_system.crt
    - /opt/blackduck/hub/blackduck-matchengine/security/blackduck_system.key
  failureThreshold: 10
  initialDelaySeconds: 240
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
{{- end -}}
{{- end -}}
