{{- $_ :=  set . "serviceName" "blackduck-scan" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: scan
  name: {{ .Release.Name }}-blackduck-scan
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-8443
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "bd.selectorLabelsWithoutVersion" . | nindent 4 }}
    component: scan
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: scan
  name: {{ .Release.Name }}-blackduck-scan
  namespace: {{ .Release.Namespace }}
spec:
  {{- if eq .Values.status "Running" }}
  replicas: {{ .Values.scan.replicas }}
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      {{- include "bd.selectorLabelsWithoutVersion" . | nindent 6 }}
      component: scan
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "bd.selectorLabels" . | nindent 8 }}
        component: scan
      annotations:
        {{- include "bd.prometheus.common.annotations" . | nindent 8 }}
        checksum/blackduck-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/postgres-config: {{ include (print $.Template.BasePath "/postgres-config.yaml") . | sha256sum }}
        {{- if .Values.scan.podAnnotations }}
        {{- range $key, $value := .Values.scan.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      name: {{ .Release.Name }}-blackduck-scan
    spec:
      {{- if .Values.enableInitContainer }}
      initContainers:
      {{- include "bd.datadog.java.initcontainer" . | indent 6 }}
      {{- include "bd.postgresql.up.check.initcontainer" . | indent 6 }}
      {{- end }}
      containers:
      - env:
        - name: HUB_MAX_MEMORY
          value: {{ include "computeHubMaxMemory" .Values.scan }}
        {{- if .Values.scan.hubMinMemory }}
        - name: HUB_MIN_MEMORY
          value: {{ .Values.scan.hubMinMemory }}
        {{- end }}
        - name: blackduck.hub.pool.max.active
        {{- if .Values.scan.dbPoolMaxActive }}
          value: {{ quote .Values.scan.dbPoolMaxActive }}
        {{- else }}
          value: {{ quote .Values.dbPoolMaxActive }}
        {{- end -}}
        {{- include "bd.datadog.java.env" . | indent 8 }}
        - name: DD_ENABLED
          value: {{ .Values.datadog.enabled | quote }}
        - name: HUB_MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
          value: {{ .Values.metrics.enabled | quote }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-config
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-db-config
        {{- if .Values.scan.registry }}
          {{- if .Values.scan.imageTag }}
        image: {{ .Values.scan.registry }}/blackduck-scan:{{ .Values.scan.imageTag }}
          {{- else }}
        image: {{ .Values.scan.registry }}/blackduck-scan:{{ .Values.imageTag }}
          {{- end}}
        {{- else }}
          {{- if .Values.scan.imageTag }}
        image: {{ .Values.registry }}/blackduck-scan:{{ .Values.scan.imageTag }}
          {{- else }}
        image: {{ .Values.registry }}/blackduck-scan:{{ .Values.imageTag }}
          {{- end}}
        {{- end}}
        {{- include "customImagePullPolicy" .Values.scan | nindent 8 }}
        {{- include "scanStartupProbe" . | nindent 8 }}
        {{- include "scanLivenessProbe" . | nindent 8 }}
        name: scan
        ports:
        - containerPort: 8443
          protocol: TCP
        resources:
          {{- toYaml .Values.scan.resources | nindent 12 }}
        {{- with .Values.scan.securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
        volumeMounts:
        {{- include "bd.ale.volumemounts" . | indent 8 }}
        {{- include "bd.datadog.java.volumemount" . | indent 8 }}
        {{- include "bd.postgresql.secrets.volumemounts" . | indent 8 }}
        - mountPath: /opt/blackduck/hub/hub-scan/security
          name: dir-scan
        {{- include "common.volume.mount" . | indent 8 }}
      dnsPolicy: ClusterFirst
      {{- include "bd.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.scan.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.scan.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.scan.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- if .Values.scan.podSecurityContext }}
      {{- with .Values.scan.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- else }}
      {{- include "bd.podSecurityContext" . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-blackduck-service-account
      restartPolicy: Always
      volumes:
      {{- include "bd.datadog.java.volume" . | indent 6 }}
      - emptyDir: {}
        name: dir-scan
      {{- include "bd.postgresql.secrets.volumes" . | indent 6 }}
      {{- include "common.volumes" . | indent 6 }}
      {{- if .Values.enableApplicationLevelEncryption }}
      {{- include "bd.ale.volumes" . | indent 6 }}
      {{- end }}

{{- define "scanStartupProbe" -}}
{{- if .Values.enableLivenessProbe -}}
startupProbe:
  exec:
    command:
    - /usr/local/bin/docker-healthcheck.sh
    - https://127.0.0.1:8443/api/health-checks/liveness
    - /opt/blackduck/hub/hub-scan/security/root.crt
    - /opt/blackduck/hub/hub-scan/security/blackduck_system.crt
    - /opt/blackduck/hub/hub-scan/security/blackduck_system.key
  failureThreshold: {{ mul .Values.maxWaitForSchemaUpdatesMinutes 2 }}
  initialDelaySeconds: 240
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
{{- end -}}
{{- end -}}

{{- define "scanLivenessProbe" -}}
{{- if .Values.enableLivenessProbe -}}
livenessProbe:
  exec:
    command:
    - /usr/local/bin/docker-healthcheck.sh
    - https://127.0.0.1:8443/api/health-checks/liveness
    - /opt/blackduck/hub/hub-scan/security/root.crt
    - /opt/blackduck/hub/hub-scan/security/blackduck_system.crt
    - /opt/blackduck/hub/hub-scan/security/blackduck_system.key
  failureThreshold: 10
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
{{- end -}}
{{- end -}}
