apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: serviceaccount

  {{- if .Values.serviceaccount.annotations }}
  annotations:
    {{ .Values.serviceaccount.annotations | toYaml}}
  {{- end }}
  name: {{ .Release.Name }}-blackduck-service-account
  namespace: {{ .Release.Namespace }}
