apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: uploadcache
  name: {{ .Release.Name }}-blackduck-uploadcache
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-9443
    port: 9443
    protocol: TCP
    targetPort: 9443
  - name: port-9444
    port: 9444
    protocol: TCP
    targetPort: 9444
  selector:
    {{- include "bd.selectorLabelsWithoutVersion" . | nindent 4 }}
    component: uploadcache
  type: ClusterIP
{{- if and .Values.enablePersistentStorage (not .Values.uploadcache.persistentVolumeClaimName) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: pvc
  name: {{ .Release.Name }}-blackduck-uploadcache-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.uploadcache.claimSize }}
  {{- if .Values.uploadcache.storageClass }}
  storageClassName: {{ .Values.uploadcache.storageClass }}
  {{- else if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end}}
  {{- if .Values.uploadcache.volumeName }}
  volumeName: {{ .Values.uploadcache.volumeName }}
  {{- end -}}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: uploadcache
  name: {{ .Release.Name }}-blackduck-uploadcache
  namespace: {{ .Release.Namespace }}
spec:
  {{- if eq .Values.status "Running" }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      {{- include "bd.selectorLabelsWithoutVersion" . | nindent 6 }}
      component: uploadcache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "bd.selectorLabels" . | nindent 8 }}
        component: uploadcache
      annotations:
        checksum/blackduck-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/postgres-config: {{ include (print $.Template.BasePath "/postgres-config.yaml") . | sha256sum }}
        checksum/uploadcache-config: {{ include (print $.Template.BasePath "/seal-key.yaml") . | sha256sum }}
      name: {{ .Release.Name }}-blackduck-uploadcache
    spec:
      {{- if .Values.enableInitContainer }}
      initContainers:
      - name: synopsys-init
        {{- if .Values.init.registry }}
        image: {{ .Values.init.registry }}/synopsys-init:{{ .Values.init.imageTag }}
        {{- else }}
        image: {{ .Values.registry }}/synopsys-init:{{ .Values.init.imageTag }}
        {{- end}}
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: HUB_POSTGRES_HOST
              name: {{ .Release.Name }}-blackduck-db-config
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: HUB_POSTGRES_PORT
              name: {{ .Release.Name }}-blackduck-db-config
        - name: POSTGRESQL_USER
          valueFrom:
            configMapKeyRef:
              key: HUB_POSTGRES_CONNECTION_ADMIN
              name: {{ .Release.Name }}-blackduck-config
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: HUB_POSTGRES_ADMIN_PASSWORD_FILE
              name: {{ .Release.Name }}-blackduck-db-creds
        - name: POSTGRES_SSL_MODE
          valueFrom:
            configMapKeyRef:
              key: HUB_POSTGRES_ENABLE_SSL
              name: {{ .Release.Name }}-blackduck-db-config
        args:
        - "--postgres-database={{ .Values.init.database }}" # Postgres database name
        - "--postgres-host=$(POSTGRES_HOST)" # Postgres database host
        - "--postgres-password=$(POSTGRESQL_PASSWORD)" # Postgres database password
        - "--postgres-port=$(POSTGRES_PORT)" # Postgres database port
        - "--postgres-user=$(POSTGRESQL_USER)" # Postgres database user
        - "--postgres-ssl-mode=$(POSTGRES_SSL_MODE)" # Postgres SSL mode
        imagePullPolicy: Always
        {{- with .Values.init.securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-config
        {{- if .Values.uploadcache.registry }}
        image: {{ .Values.uploadcache.registry }}/blackduck-upload-cache:{{ .Values.uploadcache.imageTag }}
        {{- else }}
        image: {{ .Values.registry }}/blackduck-upload-cache:{{ .Values.uploadcache.imageTag }}
        {{- end}}
        imagePullPolicy: Always
        {{- include "uploadcacheLivenessProbe" . | nindent 8 }}
        name: uploadcache
        ports:
        - containerPort: 9443
          protocol: TCP
        - containerPort: 9444
          protocol: TCP
        resources:
          {{- toYaml .Values.uploadcache.resources | nindent 12 }}
        {{- with .Values.uploadcache.securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /opt/blackduck/hub/blackduck-upload-cache/security
          name: dir-uploadcache-security
        - mountPath: /opt/blackduck/hub/blackduck-upload-cache/uploads
          name: dir-uploadcache-data
          subPath: uploads
        - mountPath: /opt/blackduck/hub/blackduck-upload-cache/keys
          name: dir-uploadcache-data
          subPath: keys
        - mountPath: /tmp/secrets
          name: dir-seal-key
      dnsPolicy: ClusterFirst
      {{- include "bd.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.uploadcache.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.uploadcache.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.uploadcache.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- if .Values.uploadcache.podSecurityContext }}
      {{- with .Values.uploadcache.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- else }}
      {{- include "bd.podSecurityContext" . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-blackduck-service-account
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: dir-uploadcache-security
      {{- include "uploadcachePersistentStorage" . | nindent 6 }}
      - name: dir-seal-key
        secret:
          defaultMode: 292
          secretName: {{ .Release.Name }}-blackduck-upload-cache


{{- define "uploadcacheLivenessProbe" -}}
{{- if .Values.enableLivenessProbe -}}
livenessProbe:
  exec:
    command:
    - curl
    - --insecure
    - -X
    - GET
    - --verbose
    - http://localhost:8086/live?full=1
  failureThreshold: 5
  initialDelaySeconds: 240
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
{{- end -}}
{{- end -}}

{{- define "uploadcachePersistentStorage" -}}
{{- if .Values.enablePersistentStorage -}}
- name: dir-uploadcache-data
  persistentVolumeClaim:
    claimName: {{if .Values.uploadcache.persistentVolumeClaimName}} {{.Values.uploadcache.persistentVolumeClaimName}} {{else}} {{ .Release.Name }}-blackduck-uploadcache-data {{end}}
{{- else -}}
- emptyDir: {}
  name: dir-uploadcache-data
{{- end -}}
{{- end -}}
