postgres:
  resources:
    requests:
      cpu: "2000m"
      memory: "12288Mi"

jobrunner:
  replicas: 6
  hubMaxMemory: "12288m"
  maxPeriodicThreads: 8
  maxPeriodicPrefetch: 4
  maxOndemandThreads: 24
  maxOndemandPrefetch: 16
  resources:
    limits:
      cpu: "1000m"
      memory: "13824Mi"

scan:
  replicas: 3
  hubMaxMemory: "8192m"
  resources:
    limits:
      memory: "9728Mi"

webapp:
  hubMaxMemory: "8192m"
  resources:
    requests:
      cpu: "2000m"
    limits:
      memory: "9728Mi"

webserver:
  resources:
    limits:
      memory: "2048Mi"

webui:
  resources:
    requests:
      cpu: "500m"
    limits:
      cpu: "1000m"
      memory: "1024Mi"

bomengine:
  replicas: 4
  hubMaxMemory: "12288m"
  resources:
    requests:
      memory: "1536Mi"
    limits:
      memory: "13824Mi"

matchengine:
  replicas: 3
  hubMaxMemory: "12288m"
  resources:
    requests:
      memory: "1536Mi"
      cpu: "500m"
    limits:
      memory: "13824Mi"
      cpu: "1000m"
